openapi: 3.0.2
info:
  contact:
    email: info@example.org
    name: Acme Corporation
    url: http://example.org/
  description: |-
    This is a sample OpenAPI definition that conforms to the conformance
    classes "Core", "GeoJSON", "HTML" and "OpenAPI 3.0" of the draft
    standard "OGC API - Features - Part 1: Core".

    This example is a generic OGC API Features definition that uses path
    parameters to describe all feature collections and all features.
    The generic OpenAPI definition does not provide any details on the
    collections or the feature content. This information is only available
    from accessing the feature collection resources.

    There is [another example](ogcapi-features-1-example2.yaml)
    that specifies each collection explicitly.
  license:
    name: CC-BY 4.0 license
    url: https://creativecommons.org/licenses/by/4.0/
  title: 'A sample API conforming to the draft standard OGC API - Features - Part
    1: Core'
  version: 1.0.0
servers:
- description: Production server
  url: https://data.example.org/
- description: Development server
  url: https://dev.example.org/
tags:
- description: essential characteristics of this API
  name: Capabilities
- description: access to data (features)
  name: Data
paths:
  /:
    get:
      description: |-
        The landing page provides links to the API definition, the conformance
        statements and to the feature collections in this dataset.
      operationId: getLandingPage
      responses:
        "200":
          content:
            application/json:
              example:
                title: Buildings in Bonn
                description: Access to data about buildings in the city of Bonn via
                  a Web API that conforms to the OGC API Features specification.
                links:
                - href: http://data.example.org/
                  rel: self
                  type: application/json
                  title: this document
                - href: http://data.example.org/api
                  rel: service-desc
                  type: application/vnd.oai.openapi+json;version=3.0
                  title: the API definition
                - href: http://data.example.org/api.html
                  rel: service-doc
                  type: text/html
                  title: the API documentation
                - href: http://data.example.org/conformance
                  rel: conformance
                  type: application/json
                  title: OGC API conformance classes implemented by this server
                - href: http://data.example.org/collections
                  rel: data
                  type: application/json
                  title: Information about the feature collections
              schema:
                $ref: '#/components/schemas/landingPage'
            text/html:
              schema:
                type: string
          description: |-
            The landing page provides links to the API definition
            (link relations `service-desc` and `service-doc`),
            the Conformance declaration (path `/conformance`,
            link relation `conformance`), and the Feature
            Collections (path `/collections`, link relation
            `data`).
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
            text/html:
              schema:
                type: string
          description: A server error occurred.
      summary: landing page
      tags:
      - Capabilities
  /conformance:
    get:
      description: |-
        A list of all conformance classes specified in a standard that the
        server conforms to.
      operationId: getConformanceDeclaration
      responses:
        "200":
          content:
            application/json:
              example:
                conformsTo:
                - http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/core
                - http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/oas30
                - http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/html
                - http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/geojson
              schema:
                $ref: '#/components/schemas/confClasses'
            text/html:
              schema:
                type: string
          description: |-
            The URIs of all conformance classes supported by the server.

            To support "generic" clients that want to access multiple
            OGC API Features implementations - and not "just" a specific
            API / server, the server declares the conformance
            classes it implements and conforms to.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
            text/html:
              schema:
                type: string
          description: A server error occurred.
      summary: information about specifications that this API conforms to
      tags:
      - Capabilities
  /collections:
    get:
      operationId: getCollections
      responses:
        "200":
          content:
            application/json:
              example:
                links:
                - href: http://data.example.org/collections.json
                  rel: self
                  type: application/json
                  title: this document
                - href: http://data.example.org/collections.html
                  rel: alternate
                  type: text/html
                  title: this document as HTML
                - href: http://schemas.example.org/1.0/buildings.xsd
                  rel: describedBy
                  type: application/xml
                  title: GML application schema for Acme Corporation building data
                - href: http://download.example.org/buildings.gpkg
                  rel: enclosure
                  type: application/geopackage+sqlite3
                  title: Bulk download (GeoPackage)
                  length: 472546
                collections:
                - id: buildings
                  title: Buildings
                  description: Buildings in the city of Bonn.
                  extent:
                    spatial:
                      bbox:
                      - - 7.01
                        - 50.63
                        - 7.22
                        - 50.78
                    temporal:
                      interval:
                      - - 2010-02-15T12:34:56Z
                        - null
                  links:
                  - href: http://data.example.org/collections/buildings/items
                    rel: items
                    type: application/geo+json
                    title: Buildings
                  - href: http://data.example.org/collections/buildings/items.html
                    rel: items
                    type: text/html
                    title: Buildings
                  - href: https://creativecommons.org/publicdomain/zero/1.0/
                    rel: license
                    type: text/html
                    title: CC0-1.0
                  - href: https://creativecommons.org/publicdomain/zero/1.0/rdf
                    rel: license
                    type: application/rdf+xml
                    title: CC0-1.0
              schema:
                $ref: '#/components/schemas/collections'
            text/html:
              schema:
                type: string
          description: |-
            The feature collections shared by this API.

            The dataset is organized as one or more feature collections. This resource
            provides information about and access to the collections.

            The response contains the list of collections. For each collection, a link
            to the items in the collection (path `/collections/{collectionId}/items`,
            link relation `items`) as well as key information about the collection.
            This information includes:

            * A local identifier for the collection that is unique for the dataset;
            * A list of coordinate reference systems (CRS) in which geometries may be returned by the server. The first CRS is the default coordinate reference system (the default is always WGS 84 with axis order longitude/latitude);
            * An optional title and description for the collection;
            * An optional extent that can be used to provide an indication of the spatial and temporal extent of the collection - typically derived from the data;
            * An optional indicator about the type of the items in the collection (the default value, if the indicator is not provided, is 'feature').
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
            text/html:
              schema:
                type: string
          description: A server error occurred.
      summary: the feature collections in the dataset
      tags:
      - Capabilities
  /collections/{collectionId}:
    get:
      operationId: describeCollection
      parameters:
      - description: local identifier of a collection
        in: path
        name: collectionId
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              example:
                id: buildings
                title: Buildings
                description: Buildings in the city of Bonn.
                extent:
                  spatial:
                    bbox:
                    - - 7.01
                      - 50.63
                      - 7.22
                      - 50.78
                  temporal:
                    interval:
                    - - 2010-02-15T12:34:56Z
                      - null
                links:
                - href: http://data.example.org/collections/buildings/items
                  rel: items
                  type: application/geo+json
                  title: Buildings
                - href: http://data.example.org/collections/buildings/items.html
                  rel: items
                  type: text/html
                  title: Buildings
                - href: https://creativecommons.org/publicdomain/zero/1.0/
                  rel: license
                  type: text/html
                  title: CC0-1.0
                - href: https://creativecommons.org/publicdomain/zero/1.0/rdf
                  rel: license
                  type: application/rdf+xml
                  title: CC0-1.0
              schema:
                $ref: '#/components/schemas/collection'
            text/html:
              schema:
                type: string
          description: |-
            Information about the feature collection with id `collectionId`.

            The response contains a link to the items in the collection
            (path `/collections/{collectionId}/items`, link relation `items`)
            as well as key information about the collection. This information
            includes:

            * A local identifier for the collection that is unique for the dataset;
            * A list of coordinate reference systems (CRS) in which geometries may be returned by the server. The first CRS is the default coordinate reference system (the default is always WGS 84 with axis order longitude/latitude);
            * An optional title and description for the collection;
            * An optional extent that can be used to provide an indication of the spatial and temporal extent of the collection - typically derived from the data;
            * An optional indicator about the type of the items in the collection (the default value, if the indicator is not provided, is 'feature').
        "404":
          description: The requested URI was not found.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
            text/html:
              schema:
                type: string
          description: A server error occurred.
      summary: describe the feature collection with id `collectionId`
      tags:
      - Capabilities
  /collections/{collectionId}/items:
    get:
      description: |-
        Fetch features of the feature collection with id `collectionId`.

        Every feature in a dataset belongs to a collection. A dataset may
        consist of multiple feature collections. A feature collection is often a
        collection of features of a similar type, based on a common schema.

        Use content negotiation to request HTML or GeoJSON.
      operationId: getFeatures
      parameters:
      - description: local identifier of a collection
        in: path
        name: collectionId
        required: true
        schema:
          type: string
      - description: |-
          The optional limit parameter limits the number of items that are presented in the response document.

          Only items are counted that are on the first level of the collection in the response document.
          Nested objects contained within the explicitly requested items shall not be counted.

          Minimum = 1. Maximum = 10000. Default = 10.
        explode: false
        in: query
        name: limit
        required: false
        schema:
          default: 10
          maximum: 10000
          minimum: 1
          type: integer
        style: form
      - description: |-
          Only features that have a geometry that intersects the bounding box are selected.
          The bounding box is provided as four or six numbers, depending on whether the
          coordinate reference system includes a vertical axis (height or depth):

          * Lower left corner, coordinate axis 1
          * Lower left corner, coordinate axis 2
          * Minimum value, coordinate axis 3 (optional)
          * Upper right corner, coordinate axis 1
          * Upper right corner, coordinate axis 2
          * Maximum value, coordinate axis 3 (optional)

          The coordinate reference system of the values is WGS 84 longitude/latitude
          (http://www.opengis.net/def/crs/OGC/1.3/CRS84) unless a different coordinate
          reference system is specified in the parameter `bbox-crs`.

          For WGS 84 longitude/latitude the values are in most cases the sequence of
          minimum longitude, minimum latitude, maximum longitude and maximum latitude.
          However, in cases where the box spans the antimeridian the first value
          (west-most box edge) is larger than the third value (east-most box edge).

          If the vertical axis is included, the third and the sixth number are
          the bottom and the top of the 3-dimensional bounding box.

          If a feature has multiple spatial geometry properties, it is the decision of the
          server whether only a single spatial geometry property is used to determine
          the extent or all relevant geometries.
        explode: false
        in: query
        name: bbox
        required: false
        schema:
          items:
            type: number
          maxItems: 6
          minItems: 4
          type: array
        style: form
      - description: |-
          Either a date-time or an interval, open or closed. Date and time expressions
          adhere to RFC 3339. Open intervals are expressed using double-dots.

          Examples:

          * A date-time: "2018-02-12T23:20:50Z"
          * A closed interval: "2018-02-12T00:00:00Z/2018-03-18T12:31:12Z"
          * Open intervals: "2018-02-12T00:00:00Z/.." or "../2018-03-18T12:31:12Z"

          Only features that have a temporal property that intersects the value of
          `datetime` are selected.

          If a feature has multiple temporal properties, it is the decision of the
          server whether only a single temporal property is used to determine
          the extent or all relevant temporal properties.
        explode: false
        in: query
        name: datetime
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/geo+json:
              example:
                type: FeatureCollection
                links:
                - href: http://data.example.com/collections/buildings/items.json
                  rel: self
                  type: application/geo+json
                  title: this document
                - href: http://data.example.com/collections/buildings/items.html
                  rel: alternate
                  type: text/html
                  title: this document as HTML
                - href: http://data.example.com/collections/buildings/items.json&offset=10&limit=2
                  rel: next
                  type: application/geo+json
                  title: next page
                timeStamp: 2018-04-03T14:52:23Z
                numberMatched: 123
                numberReturned: 2
                features:
                - type: Feature
                  id: "123"
                  geometry:
                    type: Polygon
                    coordinates:
                    - '...'
                  properties:
                    function: residential
                    floors: "2"
                    lastUpdate: 2015-08-01T12:34:56Z
                - type: Feature
                  id: "132"
                  geometry:
                    type: Polygon
                    coordinates:
                    - '...'
                  properties:
                    function: public use
                    floors: "10"
                    lastUpdate: 2013-12-03T10:15:37Z
              schema:
                $ref: '#/components/schemas/featureCollectionGeoJSON'
            text/html:
              schema:
                type: string
          description: |-
            The response is a document consisting of features in the collection.
            The features included in the response are determined by the server
            based on the query parameters of the request. To support access to
            larger collections without overloading the client, the API supports
            paged access with links to the next page, if more features are selected
            that the page size.

            The `bbox` and `datetime` parameter can be used to select only a
            subset of the features in the collection (the features that are in the
            bounding box or time interval). The `bbox` parameter matches all features
            in the collection that are not associated with a location, too. The
            `datetime` parameter matches all features in the collection that are
            not associated with a time stamp or interval, too.

            The `limit` parameter may be used to control the subset of the
            selected features that should be returned in the response, the page size.
            Each page may include information about the number of selected and
            returned features (`numberMatched` and `numberReturned`) as well as
            links to support paging (link relation `next`).
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
            text/html:
              schema:
                type: string
          description: A query parameter has an invalid value.
        "404":
          description: The requested URI was not found.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
            text/html:
              schema:
                type: string
          description: A server error occurred.
      summary: fetch features
      tags:
      - Data
  /collections/{collectionId}/items/{featureId}:
    get:
      description: |-
        Fetch the feature with id `featureId` in the feature collection
        with id `collectionId`.

        Use content negotiation to request HTML or GeoJSON.
      operationId: getFeature
      parameters:
      - description: local identifier of a collection
        in: path
        name: collectionId
        required: true
        schema:
          type: string
      - description: local identifier of a feature
        in: path
        name: featureId
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/geo+json:
              example:
                type: Feature
                links:
                - href: http://data.example.com/id/building/123
                  rel: canonical
                  title: canonical URI of the building
                - href: http://data.example.com/collections/buildings/items/123.json
                  rel: self
                  type: application/geo+json
                  title: this document
                - href: http://data.example.com/collections/buildings/items/123.html
                  rel: alternate
                  type: text/html
                  title: this document as HTML
                - href: http://data.example.com/collections/buildings
                  rel: collection
                  type: application/geo+json
                  title: the collection document
                id: "123"
                geometry:
                  type: Polygon
                  coordinates:
                  - '...'
                properties:
                  function: residential
                  floors: "2"
                  lastUpdate: 2015-08-01T12:34:56Z
              schema:
                $ref: '#/components/schemas/featureGeoJSON'
            text/html:
              schema:
                type: string
          description: |-
            fetch the feature with id `featureId` in the feature collection
            with id `collectionId`
        "404":
          description: The requested URI was not found.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
            text/html:
              schema:
                type: string
          description: A server error occurred.
      summary: fetch a single feature
      tags:
      - Data
components:
  schemas:
    landingPage:
      example:
        description: Access to data about buildings in the city of Bonn via a Web
          API that conforms to the OGC API Features specification.
        links:
        - hreflang: en
          rel: alternate
          length: 0
          href: http://data.example.com/buildings/123
          type: application/geo+json
          title: Trierer Strasse 70, 53115 Bonn
        - hreflang: en
          rel: alternate
          length: 0
          href: http://data.example.com/buildings/123
          type: application/geo+json
          title: Trierer Strasse 70, 53115 Bonn
        title: Buildings in Bonn
      properties:
        title:
          example: Buildings in Bonn
          type: string
        description:
          example: Access to data about buildings in the city of Bonn via a Web API
            that conforms to the OGC API Features specification.
          type: string
        links:
          items:
            $ref: '#/components/schemas/link'
          type: array
      required:
      - links
      type: object
    link:
      example:
        hreflang: en
        rel: alternate
        length: 0
        href: http://data.example.com/buildings/123
        type: application/geo+json
        title: Trierer Strasse 70, 53115 Bonn
      properties:
        href:
          example: http://data.example.com/buildings/123
          type: string
        rel:
          example: alternate
          type: string
        type:
          example: application/geo+json
          type: string
        hreflang:
          example: en
          type: string
        title:
          example: Trierer Strasse 70, 53115 Bonn
          type: string
        length:
          type: integer
      required:
      - href
      type: object
    exception:
      description: 'Information about the exception: an error code plus an optional
        description.'
      properties:
        code:
          type: string
        description:
          type: string
      required:
      - code
      type: object
    confClasses:
      example:
        conformsTo:
        - conformsTo
        - conformsTo
      properties:
        conformsTo:
          items:
            type: string
          type: array
      required:
      - conformsTo
      type: object
    collections:
      example:
        collections:
        - extent:
            spatial:
              crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
              bbox:
              - - -180
                - -90
                - 180
                - 90
              - - -180
                - -90
                - 180
                - 90
            temporal:
              trs: http://www.opengis.net/def/uom/ISO-8601/0/Gregorian
              interval:
              - - 2011-11-11T12:22:11Z
                - null
              - - 2011-11-11T12:22:11Z
                - null
          itemType: feature
          crs:
          - http://www.opengis.net/def/crs/OGC/1.3/CRS84
          - http://www.opengis.net/def/crs/EPSG/0/4326
          description: An address.
          links:
          - href: http://data.example.com/buildings
            rel: item
          - href: http://example.com/concepts/buildings.html
            rel: describedBy
            type: text/html
          id: address
          title: address
        - extent:
            spatial:
              crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
              bbox:
              - - -180
                - -90
                - 180
                - 90
              - - -180
                - -90
                - 180
                - 90
            temporal:
              trs: http://www.opengis.net/def/uom/ISO-8601/0/Gregorian
              interval:
              - - 2011-11-11T12:22:11Z
                - null
              - - 2011-11-11T12:22:11Z
                - null
          itemType: feature
          crs:
          - http://www.opengis.net/def/crs/OGC/1.3/CRS84
          - http://www.opengis.net/def/crs/EPSG/0/4326
          description: An address.
          links:
          - href: http://data.example.com/buildings
            rel: item
          - href: http://example.com/concepts/buildings.html
            rel: describedBy
            type: text/html
          id: address
          title: address
        links:
        - hreflang: en
          rel: alternate
          length: 0
          href: http://data.example.com/buildings/123
          type: application/geo+json
          title: Trierer Strasse 70, 53115 Bonn
        - hreflang: en
          rel: alternate
          length: 0
          href: http://data.example.com/buildings/123
          type: application/geo+json
          title: Trierer Strasse 70, 53115 Bonn
      properties:
        links:
          items:
            $ref: '#/components/schemas/link'
          type: array
        collections:
          items:
            $ref: '#/components/schemas/collection'
          type: array
      required:
      - collections
      - links
      type: object
    collection:
      example:
        extent:
          spatial:
            crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            bbox:
            - - -180
              - -90
              - 180
              - 90
            - - -180
              - -90
              - 180
              - 90
          temporal:
            trs: http://www.opengis.net/def/uom/ISO-8601/0/Gregorian
            interval:
            - - 2011-11-11T12:22:11Z
              - null
            - - 2011-11-11T12:22:11Z
              - null
        itemType: feature
        crs:
        - http://www.opengis.net/def/crs/OGC/1.3/CRS84
        - http://www.opengis.net/def/crs/EPSG/0/4326
        description: An address.
        links:
        - href: http://data.example.com/buildings
          rel: item
        - href: http://example.com/concepts/buildings.html
          rel: describedBy
          type: text/html
        id: address
        title: address
      properties:
        id:
          description: identifier of the collection used, for example, in URIs
          example: address
          type: string
        title:
          description: human readable title of the collection
          example: address
          type: string
        description:
          description: a description of the features in the collection
          example: An address.
          type: string
        links:
          example:
          - href: http://data.example.com/buildings
            rel: item
          - href: http://example.com/concepts/buildings.html
            rel: describedBy
            type: text/html
          items:
            $ref: '#/components/schemas/link'
          type: array
        extent:
          $ref: '#/components/schemas/extent'
        itemType:
          default: feature
          description: indicator about the type of the items in the collection (the
            default value is 'feature').
          type: string
        crs:
          default:
          - http://www.opengis.net/def/crs/OGC/1.3/CRS84
          description: the list of coordinate reference systems supported by the service
          example:
          - http://www.opengis.net/def/crs/OGC/1.3/CRS84
          - http://www.opengis.net/def/crs/EPSG/0/4326
          items:
            type: string
          type: array
      required:
      - id
      - links
      type: object
    extent:
      description: |-
        The extent of the features in the collection. In the Core only spatial and temporal
        extents are specified. Extensions may add additional members to represent other
        extents, for example, thermal or pressure ranges.
      example:
        spatial:
          crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
          bbox:
          - - -180
            - -90
            - 180
            - 90
          - - -180
            - -90
            - 180
            - 90
        temporal:
          trs: http://www.opengis.net/def/uom/ISO-8601/0/Gregorian
          interval:
          - - 2011-11-11T12:22:11Z
            - null
          - - 2011-11-11T12:22:11Z
            - null
      properties:
        spatial:
          $ref: '#/components/schemas/extent_spatial'
        temporal:
          $ref: '#/components/schemas/extent_temporal'
      type: object
    featureCollectionGeoJSON:
      example:
        timeStamp: 2017-08-17T08:05:32Z
        features:
        - links:
          - hreflang: en
            rel: alternate
            length: 0
            href: http://data.example.com/buildings/123
            type: application/geo+json
            title: Trierer Strasse 70, 53115 Bonn
          - hreflang: en
            rel: alternate
            length: 0
            href: http://data.example.com/buildings/123
            type: application/geo+json
            title: Trierer Strasse 70, 53115 Bonn
          id: ""
          type: Feature
          properties: '{}'
        - links:
          - hreflang: en
            rel: alternate
            length: 0
            href: http://data.example.com/buildings/123
            type: application/geo+json
            title: Trierer Strasse 70, 53115 Bonn
          - hreflang: en
            rel: alternate
            length: 0
            href: http://data.example.com/buildings/123
            type: application/geo+json
            title: Trierer Strasse 70, 53115 Bonn
          id: ""
          type: Feature
          properties: '{}'
        numberReturned: 10
        links:
        - hreflang: en
          rel: alternate
          length: 0
          href: http://data.example.com/buildings/123
          type: application/geo+json
          title: Trierer Strasse 70, 53115 Bonn
        - hreflang: en
          rel: alternate
          length: 0
          href: http://data.example.com/buildings/123
          type: application/geo+json
          title: Trierer Strasse 70, 53115 Bonn
        type: FeatureCollection
        numberMatched: 127
      properties:
        type:
          enum:
          - FeatureCollection
          type: string
        features:
          items:
            $ref: '#/components/schemas/featureGeoJSON'
          type: array
        links:
          items:
            $ref: '#/components/schemas/link'
          type: array
        timeStamp:
          description: This property indicates the time and date when the response
            was generated.
          example: 2017-08-17T08:05:32Z
          format: date-time
          type: string
        numberMatched:
          description: |-
            The number of features of the feature type that match the selection
            parameters like `bbox`.
          example: 127
          minimum: 0
          type: integer
        numberReturned:
          description: |-
            The number of features in the feature collection.

            A server may omit this information in a response, if the information
            about the number of features is not known or difficult to compute.

            If the value is provided, the value shall be identical to the number
            of items in the "features" array.
          example: 10
          minimum: 0
          type: integer
      required:
      - features
      - type
      type: object
    featureGeoJSON:
      example:
        links:
        - hreflang: en
          rel: alternate
          length: 0
          href: http://data.example.com/buildings/123
          type: application/geo+json
          title: Trierer Strasse 70, 53115 Bonn
        - hreflang: en
          rel: alternate
          length: 0
          href: http://data.example.com/buildings/123
          type: application/geo+json
          title: Trierer Strasse 70, 53115 Bonn
        id: ""
        type: Feature
        properties: '{}'
      properties:
        type:
          enum:
          - Feature
          type: string
        geometry:
          $ref: '#/components/schemas/geometryGeoJSON'
        properties:
          nullable: true
          type: object
        id:
          oneOf:
          - type: string
          - type: integer
        links:
          items:
            $ref: '#/components/schemas/link'
          type: array
      required:
      - geometry
      - properties
      - type
      type: object
    geometryGeoJSON:
      oneOf:
      - $ref: '#/components/schemas/pointGeoJSON'
      - $ref: '#/components/schemas/multipointGeoJSON'
      - $ref: '#/components/schemas/linestringGeoJSON'
      - $ref: '#/components/schemas/multilinestringGeoJSON'
      - $ref: '#/components/schemas/polygonGeoJSON'
      - $ref: '#/components/schemas/multipolygonGeoJSON'
      - $ref: '#/components/schemas/geometrycollectionGeoJSON'
    pointGeoJSON:
      properties:
        type:
          enum:
          - Point
          type: string
        coordinates:
          items:
            type: number
          minItems: 2
          type: array
      required:
      - coordinates
      - type
      type: object
    multipointGeoJSON:
      properties:
        type:
          enum:
          - MultiPoint
          type: string
        coordinates:
          items:
            items:
              type: number
            minItems: 2
            type: array
          type: array
      required:
      - coordinates
      - type
      type: object
    linestringGeoJSON:
      properties:
        type:
          enum:
          - LineString
          type: string
        coordinates:
          items:
            items:
              type: number
            minItems: 2
            type: array
          minItems: 2
          type: array
      required:
      - coordinates
      - type
      type: object
    multilinestringGeoJSON:
      properties:
        type:
          enum:
          - MultiLineString
          type: string
        coordinates:
          items:
            items:
              items:
                type: number
              minItems: 2
              type: array
            minItems: 2
            type: array
          type: array
      required:
      - coordinates
      - type
      type: object
    polygonGeoJSON:
      properties:
        type:
          enum:
          - Polygon
          type: string
        coordinates:
          items:
            items:
              items:
                type: number
              minItems: 2
              type: array
            minItems: 4
            type: array
          type: array
      required:
      - coordinates
      - type
      type: object
    multipolygonGeoJSON:
      properties:
        type:
          enum:
          - MultiPolygon
          type: string
        coordinates:
          items:
            items:
              items:
                items:
                  type: number
                minItems: 2
                type: array
              minItems: 4
              type: array
            type: array
          type: array
      required:
      - coordinates
      - type
      type: object
    geometrycollectionGeoJSON:
      properties:
        type:
          enum:
          - GeometryCollection
          type: string
        geometries:
          items:
            $ref: '#/components/schemas/geometryGeoJSON'
          type: array
      required:
      - geometries
      - type
      type: object
    timeStamp:
      description: This property indicates the time and date when the response was
        generated.
      example: 2017-08-17T08:05:32Z
      format: date-time
      type: string
    numberMatched:
      description: |-
        The number of features of the feature type that match the selection
        parameters like `bbox`.
      example: 127
      minimum: 0
      type: integer
    numberReturned:
      description: |-
        The number of features in the feature collection.

        A server may omit this information in a response, if the information
        about the number of features is not known or difficult to compute.

        If the value is provided, the value shall be identical to the number
        of items in the "features" array.
      example: 10
      minimum: 0
      type: integer
    extent_spatial:
      description: The spatial extent of the features in the collection.
      example:
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        bbox:
        - - -180
          - -90
          - 180
          - 90
        - - -180
          - -90
          - 180
          - 90
      properties:
        bbox:
          description: |-
            One or more bounding boxes that describe the spatial extent of the dataset.
            In the Core only a single bounding box is supported. Extensions may support
            additional areas. If multiple areas are provided, the union of the bounding
            boxes describes the spatial extent.
          items:
            description: |-
              Each bounding box is provided as four or six numbers, depending on
              whether the coordinate reference system includes a vertical axis
              (height or depth):

              * Lower left corner, coordinate axis 1
              * Lower left corner, coordinate axis 2
              * Minimum value, coordinate axis 3 (optional)
              * Upper right corner, coordinate axis 1
              * Upper right corner, coordinate axis 2
              * Maximum value, coordinate axis 3 (optional)

              The coordinate reference system of the values is WGS 84 longitude/latitude
              (http://www.opengis.net/def/crs/OGC/1.3/CRS84) unless a different coordinate
              reference system is specified in `crs`.

              For WGS 84 longitude/latitude the values are in most cases the sequence of
              minimum longitude, minimum latitude, maximum longitude and maximum latitude.
              However, in cases where the box spans the antimeridian the first value
              (west-most box edge) is larger than the third value (east-most box edge).

              If the vertical axis is included, the third and the sixth number are
              the bottom and the top of the 3-dimensional bounding box.

              If a feature has multiple spatial geometry properties, it is the decision of the
              server whether only a single spatial geometry property is used to determine
              the extent or all relevant geometries.
            example:
            - -180
            - -90
            - 180
            - 90
            items:
              type: number
            maxItems: 6
            minItems: 4
            type: array
          minItems: 1
          type: array
        crs:
          default: http://www.opengis.net/def/crs/OGC/1.3/CRS84
          description: |-
            Coordinate reference system of the coordinates in the spatial extent
            (property `bbox`). The default reference system is WGS 84 longitude/latitude.
            In the Core this is the only supported coordinate reference system.
            Extensions may support additional coordinate reference systems and add
            additional enum values.
          enum:
          - http://www.opengis.net/def/crs/OGC/1.3/CRS84
          type: string
    extent_temporal:
      description: The temporal extent of the features in the collection.
      example:
        trs: http://www.opengis.net/def/uom/ISO-8601/0/Gregorian
        interval:
        - - 2011-11-11T12:22:11Z
          - null
        - - 2011-11-11T12:22:11Z
          - null
      properties:
        interval:
          description: |-
            One or more time intervals that describe the temporal extent of the dataset.
            The value `null` is supported and indicates an open time intervall.
            In the Core only a single time interval is supported. Extensions may support
            multiple intervals. If multiple intervals are provided, the union of the
            intervals describes the temporal extent.
          items:
            description: |-
              Begin and end times of the time interval. The timestamps
              are in the coordinate reference system specified in `trs`. By default
              this is the Gregorian calendar.
            example:
            - 2011-11-11T12:22:11Z
            - null
            items:
              format: date-time
              nullable: true
              type: string
            maxItems: 2
            minItems: 2
            type: array
          minItems: 1
          type: array
        trs:
          default: http://www.opengis.net/def/uom/ISO-8601/0/Gregorian
          description: |-
            Coordinate reference system of the coordinates in the temporal extent
            (property `interval`). The default reference system is the Gregorian calendar.
            In the Core this is the only supported temporal reference system.
            Extensions may support additional temporal reference systems and add
            additional enum values.
          enum:
          - http://www.opengis.net/def/uom/ISO-8601/0/Gregorian
          type: string

